### ISSUE TITLE
/commands error message after using your version of rolltracker

### ISSUE THREAD

**Issue by Nullsloth** [sethmccauley/Addons#1]
Not sure if its a addon conflict, but using this caused an issue with my game. Anytime I used a /command I got an error has occurred message even if ability went off. I'm positive it was this addon I removed it and it stopped. Just wanted to let you know.
![1234](https://user-images.githubusercontent.com/16423749/42732434-3ae61502-87e7-11e8-9710-1396ce94449e.png)
![capture](https://user-images.githubusercontent.com/16423749/42732435-3d568362-87e7-11e8-9a2a-0f0fc31a5bce.PNG)

**Comment by sethmccauley** [comment]
You're seeing the same thing I get. I think it was an issue in the first version of rolltracker as well. 

I tracked down the culprit and will attempt to clean it up in this version.
